# Generated by Django 5.2.1 on 2026-01-01 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_alter_examschedule_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('department', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Faculty',
            },
        ),
        migrations.DeleteModel(
            name='ExamSchedule',
        ),
        migrations.RemoveField(
            model_name='session',
            name='certificate_generated',
        ),
        migrations.RemoveField(
            model_name='session',
            name='correct_answers',
        ),
        migrations.RemoveField(
            model_name='session',
            name='exam_completed',
        ),
        migrations.RemoveField(
            model_name='session',
            name='exam_score',
        ),
        migrations.RemoveField(
            model_name='session',
            name='total_questions',
        ),
    ]
