# Generated by Django 5.2.1 on 2026-01-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_faculty_delete_examschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='designation',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
