# Generated by Django 5.2.1 on 2026-01-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_course_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='study_hours',
            field=models.FloatField(default=4),
        ),
    ]
