# Generated by Django 5.2.1 on 2025-10-31 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_examschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examschedule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
