# Generated by Django 5.2.1 on 2026-01-03 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0011_exam_examattempt_question_testcase_examassignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=50)),
                ('student_name', models.CharField(blank=True, max_length=128, null=True)),
                ('mcq_answers', models.JSONField(blank=True, default=dict)),
                ('coding_answers', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('violations', models.JSONField(blank=True, default=list)),
                ('violation_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('attempting', 'Attempting'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='attempting', max_length=20)),
                ('score', models.FloatField(blank=True, null=True)),
                ('total_marks', models.FloatField(blank=True, null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='monitor.exam')),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('exam', 'roll_number')},
            },
        ),
    ]
